# Generated by Django 5.2.8 on 2025-11-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_uploadedimage_all_expressions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=255)),
                ('video_duration', models.IntegerField(help_text='Duration in seconds')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CapturedFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='captures/')),
                ('timestamp', models.FloatField(help_text='Video timestamp in seconds')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('expression', models.CharField(blank=True, max_length=50, null=True)),
                ('expression_confidence', models.FloatField(blank=True, null=True)),
                ('all_expressions', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='quickstart.videosession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
