# Generated by Django 5.2.8 on 2025-11-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0004_remove_videosession_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='report_data',
            field=models.JSONField(blank=True, help_text='Cached session report', null=True),
        ),
    ]
