# Generated by Django 5.2.8 on 2025-12-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_preprocessedimage_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedframe',
            name='all_expressions',
        ),
        migrations.RemoveField(
            model_name='capturedframe',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='capturedframe',
            name='expression_confidence',
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='all_expressions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='expression',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='preprocessedimage',
            name='expression_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
