# Generated by Django 5.2.8 on 2025-12-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_capturedframe_all_expressions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
