# Generated by Django 5.2.8 on 2025-11-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='all_expressions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='expression',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='expression_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
