# Generated by Django 5.2.8 on 2026-01-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0009_delete_uploadedimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='videocategory',
            name='description',
        ),
    ]
