# Generated by Django 5.2.8 on 2026-01-06 11:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0010_remove_videocategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
