# Generated by Django 5.2.8 on 2026-01-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0012_sessionreport_alter_capturedframe_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturedframe',
            name='all_expressions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='expression',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='expression_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capturedframe',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='preprocessed/'),
        ),
        migrations.DeleteModel(
            name='PreprocessedImage',
        ),
    ]
