# Generated by Django 5.2.8 on 2026-01-10 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotions', '0013_capturedframe_all_expressions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturedframe',
            name='all_expressions',
        ),
        migrations.RemoveField(
            model_name='capturedframe',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='capturedframe',
            name='expression_confidence',
        ),
        migrations.RemoveField(
            model_name='capturedframe',
            name='processed_image',
        ),
        migrations.CreateModel(
            name='PreprocessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='preprocessed/')),
                ('expression', models.CharField(max_length=50)),
                ('expression_confidence', models.FloatField()),
                ('all_expressions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_version', to='emotions.capturedframe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_images', to='emotions.sessionreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_images', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preprocessed_images', to='emotions.video')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
